name: Update README

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Update README
      run: |
        # Update the timestamp in README
        sed -i "s/Last updated: .*/Last updated: $(date +'%Y-%m-%d %H:%M:%S UTC')/g" README.md
        
        # Check if there are any changes
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "📊 Auto-update README stats" || exit 0
          git push
        fi
